id: "627223e9"
name: great_plains
manufacturer: TODO
vt_version: TODO
source: |
  Attachment to Open-Agriculture/AgIsoVirtualTerminal issue #157.
  Formerly iop/unsorted/AGISOVIRTUALTERMINAL_great_plains.iop.
  File: https://github.com/user-attachments/files/24411217/great_plains.iop.zip!great_plains.iop
public: false
render:
  data_mask_size: TODO
  softkey_count: TODO
  softkey_width: TODO
  softkey_height: TODO
known_issues:
  - https://github.com/Open-Agriculture/AgIsoVirtualTerminal/issues/157
